baseURL = "https://blog.dejanvukov.com/"
languageCode = "en-us"
title = "Dejan Vuković"
theme = "PaperMod"

[params]
  comments = true
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Dejan's blog"
  Content = "Notes on things I build."

[[menu.main]]
  name = "Home"
  url = "https://dejanvukov.com/"
  weight = 1
